(function(){
  const db=window.shelfTalkDB;
  const gate=document.getElementById('dashboardGate'), app=document.getElementById('dashboardApp');
  const state={authors:[],books:[],featured:[],spotlights:[],interviews:[],metrics:[],requests:[]};
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const slug=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  const dt=v=>v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
  const localISO=v=>v?new Date(v).toISOString():null;
  function msg(id,text,ok=true){const n=$(id);if(n){n.textContent=text;n.style.color=ok?'inherit':'#b42318';}}
  function reset(id){$(id)?.reset(); const hidden=$(id)?.querySelector('input[type=hidden]');if(hidden)hidden.value='';}
  async function count(table){const {count,error}=await db.from(table).select('*',{count:'exact',head:true});return error?'—':(count??0).toLocaleString();}
  async function load(){
    const [a,b,f,s,i,m,r]=await Promise.all([
      db.from('authors').select('*').order('name'), db.from('books').select('*').order('title'),
      db.from('featured_books').select('*,books(title)').order('starts_at',{ascending:false}),
      db.from('spotlights').select('*,authors(name)').order('starts_at',{ascending:false}),
      db.from('interviews').select('*,authors(name)').order('published_at',{ascending:false}),
      db.from('impact_metrics').select('*').order('metric_key'), db.from('service_requests').select('*').order('created_at',{ascending:false})
    ]);
    state.authors=a.data||[];state.books=b.data||[];state.featured=f.data||[];state.spotlights=s.data||[];state.interviews=i.data||[];state.metrics=m.data||[];state.requests=r.data||[];
    renderAll();
    $('statBooks').textContent=await count('books');$('statAuthors').textContent=await count('authors');$('statInterviews').textContent=await count('interviews');$('statRequests').textContent=await count('service_requests');
  }
  function options(arr,placeholder){return `<option value="">${placeholder}</option>`+arr.map(x=>`<option value="${x.id}">${esc(x.name||x.title)}</option>`).join('');}
  function renderAll(){
    $('bookAuthor').innerHTML=options(state.authors,'Select author (optional)');$('featuredBook').innerHTML=options(state.books,'Select a book');$('spotlightAuthor').innerHTML=options(state.authors,'Select author');$('interviewAuthor').innerHTML=options(state.authors,'Select author (optional)');
    $('booksTable').innerHTML=state.books.length?state.books.map(b=>`<tr><td><img class="mini-thumb" src="${esc(b.cover_url||'assets/shelftalk-logo.jpg')}" alt="">${esc(b.title)}</td><td>${esc(b.author_name||state.authors.find(a=>a.id===b.author_id)?.name||'—')}</td><td><span class="status-pill">${esc(b.status)}</span></td><td><button class="table-action" data-edit-book="${b.id}">Edit</button> · <button class="table-action" data-delete-book="${b.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-row">No books yet.</td></tr>`;
    $('authorsTable').innerHTML=state.authors.length?state.authors.map(a=>`<tr><td><img class="mini-thumb" src="${esc(a.image_url||'assets/shelftalk-logo.jpg')}" alt="">${esc(a.name)}</td><td>${esc(a.country||'—')}</td><td><span class="status-pill">${esc(a.status)}</span></td><td><button class="table-action" data-edit-author="${a.id}">Edit</button> · <button class="table-action" data-delete-author="${a.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-row">No authors yet.</td></tr>`;
    $('featuredTable').innerHTML=state.featured.length?state.featured.map(f=>`<tr><td>${esc(f.books?.title||'—')}</td><td>${esc(f.feature_type)}</td><td>${dt(f.starts_at)}${f.ends_at?' → '+dt(f.ends_at):''}</td><td><button class="table-action" data-delete-featured="${f.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-row">No featured programming scheduled.</td></tr>`;
    $('spotlightsTable').innerHTML=state.spotlights.length?state.spotlights.map(s=>`<tr><td>${esc(s.authors?.name||'—')}</td><td>${esc(s.title)}</td><td>${dt(s.starts_at)}</td><td><button class="table-action" data-delete-spotlight="${s.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-row">No spotlights scheduled.</td></tr>`;
    $('interviewsTable').innerHTML=state.interviews.length?state.interviews.map(i=>`<tr><td>${esc(i.title)}</td><td>${esc(i.authors?.name||'—')}</td><td><span class="status-pill">Published</span></td><td><button class="table-action" data-delete-interview="${i.id}">Delete</button></td></tr>`).join(''):`<tr><td colspan="4" class="empty-row">No interviews yet.</td></tr>`;
    $('metricsFields').innerHTML=state.metrics.length?state.metrics.map(m=>`<label style="display:block;margin-bottom:14px;font-weight:650">${esc(m.display_label)}<input class="metric-input" data-metric-id="${m.id}" type="number" min="0" value="${Number(m.metric_value)||0}" style="display:block;width:100%;box-sizing:border-box;margin-top:7px;padding:11px;border:1px solid #d9d2c8;border-radius:10px;font:inherit"></label>`).join(''):`<p>No metrics found. Run the schema seed section first.</p>`;
    $('requestsTable').innerHTML=state.requests.length?state.requests.map(r=>`<tr><td>${esc(r.author_name)}</td><td>${esc(r.service)}</td><td>${esc(r.email)}</td><td><select class="request-status" data-request-id="${r.id}"><option ${r.status==='new'?'selected':''}>new</option><option ${r.status==='in_progress'?'selected':''}>in_progress</option><option ${r.status==='completed'?'selected':''}>completed</option><option ${r.status==='closed'?'selected':''}>closed</option></select></td><td><button class="table-action" data-save-request="${r.id}">Save</button></td></tr>`).join(''):`<tr><td colspan="5" class="empty-row">No service requests.</td></tr>`;
  }
  async function saveBook(e){e.preventDefault();let links=[];try{links=JSON.parse($('bookLinks').value||'[]')}catch{msg('bookStatusMsg','Access links must be valid JSON.',false);return}const id=$('bookId').value;const payload={title:$('bookTitle').value,slug:$('bookSlug').value||slug($('bookTitle').value),author_id:$('bookAuthor').value||null,author_name:$('bookAuthorName').value||null,genre:$('bookGenre').value||null,country:$('bookCountry').value||null,isbn:$('bookIsbn').value||null,rating:$('bookRating').value?Number($('bookRating').value):null,cover_url:$('bookCover').value||null,access_links:links,description:$('bookDescription').value||null,status:$('bookStatus').value,badge:$('bookBadge').value||null,published_date:$('bookPublishedDate').value||null,is_weekly_pick:$('bookWeeklyPick').checked,is_monthly_pick:$('bookMonthlyPick').checked};const q=id?db.from('books').update(payload).eq('id',id):db.from('books').insert(payload);const {error}=await q;if(error)msg('bookStatusMsg',error.message,false);else{msg('bookStatusMsg','Book saved.');reset('bookForm');await load()}}
  async function saveAuthor(e){e.preventDefault();const id=$('authorId').value;const payload={name:$('authorName').value,slug:$('authorSlug').value||slug($('authorName').value),country:$('authorCountry').value||null,role:$('authorRole').value||null,image_url:$('authorImage').value||null,website_url:$('authorWebsite').value||null,bio:$('authorBio').value||null,status:$('authorStatus').value};const q=id?db.from('authors').update(payload).eq('id',id):db.from('authors').insert(payload);const {error}=await q;if(error)msg('authorStatusMsg',error.message,false);else{msg('authorStatusMsg','Author saved.');reset('authorForm');await load()}}
  async function saveFeatured(e){e.preventDefault();const {error}=await db.from('featured_books').insert({book_id:$('featuredBook').value,feature_type:$('featureType').value,starts_at:localISO($('featureStart').value),ends_at:localISO($('featureEnd').value),editorial_note:$('featureNote').value||null});if(error)msg('featuredStatusMsg',error.message,false);else{msg('featuredStatusMsg','Feature scheduled.');reset('featuredForm');await load()}}
  async function saveSpotlight(e){e.preventDefault();const {error}=await db.from('spotlights').insert({author_id:$('spotlightAuthor').value,title:$('spotlightTitle').value,starts_at:localISO($('spotlightStart').value),ends_at:localISO($('spotlightEnd').value),image_url:$('spotlightImage').value||null,description:$('spotlightDescription').value||null,status:$('spotlightStatus').value});if(error)msg('spotlightStatusMsg',error.message,false);else{msg('spotlightStatusMsg','Spotlight scheduled.');reset('spotlightForm');await load()}}
  async function saveInterview(e){e.preventDefault();const {data,error}=await db.from('interviews').insert({author_id:$('interviewAuthor').value||null,title:$('interviewTitle').value,slug:$('interviewSlug').value||slug($('interviewTitle').value),published_at:localISO($('interviewPublished').value),duration_seconds:$('interviewDuration').value?Number($('interviewDuration').value):null,status:$('interviewStatus').value,thumbnail_url:$('interviewThumb').value||null,description:$('interviewDescription').value||null}).select().single();if(error){msg('interviewStatusMsg',error.message,false);return}const links=[['youtube',$('youtubeUrl').value],['spotify',$('spotifyUrl').value],['apple_podcasts',$('appleUrl').value],['shelftalk',$('shelftalkUrl').value]].filter(x=>x[1]).map(x=>({interview_id:data.id,platform:x[0],url:x[1]}));if(links.length){const r=await db.from('interview_platforms').insert(links);if(r.error){msg('interviewStatusMsg',r.error.message,false);return}}msg('interviewStatusMsg','Interview published.');reset('interviewForm');await load()}
  async function saveMetrics(e){e.preventDefault();const inputs=[...document.querySelectorAll('.metric-input')];const results=await Promise.all(inputs.map(i=>db.from('impact_metrics').update({metric_value:Number(i.value)||0,updated_at:new Date().toISOString()}).eq('id',i.dataset.metricId)));const bad=results.find(r=>r.error);msg('metricsStatusMsg',bad?bad.error.message:'Impact counters saved.',!bad);await load()}
  document.querySelectorAll('.admin-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('panel-'+b.dataset.panel).classList.add('active')}));
  document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`[data-panel="${b.dataset.go}"]`)?.click()));
  document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',()=>reset(b.dataset.reset)));
  $('bookForm').addEventListener('submit',saveBook);$('authorForm').addEventListener('submit',saveAuthor);$('featuredForm').addEventListener('submit',saveFeatured);$('spotlightForm').addEventListener('submit',saveSpotlight);$('interviewForm').addEventListener('submit',saveInterview);$('metricsForm').addEventListener('submit',saveMetrics);$('refreshAll').addEventListener('click',load);
  document.addEventListener('click',async e=>{
    const t=e.target;
    if(t.dataset.editBook){const b=state.books.find(x=>x.id===t.dataset.editBook);if(!b)return;$('bookId').value=b.id;$('bookTitle').value=b.title;$('bookSlug').value=b.slug;$('bookAuthor').value=b.author_id||'';$('bookAuthorName').value=b.author_name||'';$('bookGenre').value=b.genre||'';$('bookCountry').value=b.country||'';$('bookIsbn').value=b.isbn||'';$('bookRating').value=b.rating||'';$('bookCover').value=b.cover_url||'';$('bookLinks').value=JSON.stringify(b.access_links||[],null,2);$('bookDescription').value=b.description||'';$('bookStatus').value=b.status;$('bookBadge').value=b.badge||'';$('bookPublishedDate').value=b.published_date||'';$('bookWeeklyPick').checked=b.is_weekly_pick||false;$('bookMonthlyPick').checked=b.is_monthly_pick||false;document.querySelector('[data-panel="books"]').click();window.scrollTo({top:document.getElementById('panel-books').offsetTop-20,behavior:'smooth'})}
    if(t.dataset.editAuthor){const a=state.authors.find(x=>x.id===t.dataset.editAuthor);if(!a)return;$('authorId').value=a.id;$('authorName').value=a.name;$('authorSlug').value=a.slug;$('authorCountry').value=a.country||'';$('authorRole').value=a.role||'';$('authorImage').value=a.image_url||'';$('authorWebsite').value=a.website_url||'';$('authorBio').value=a.bio||'';$('authorStatus').value=a.status;document.querySelector('[data-panel="authors"]').click();window.scrollTo({top:document.getElementById('panel-authors').offsetTop-20,behavior:'smooth'})}
    for(const key of ['book','author','featured','spotlight','interview']){const id=t.dataset['delete'+key.charAt(0).toUpperCase()+key.slice(1)];if(id){if(!confirm('Delete this item?'))return;const table=key==='featured'?'featured_books':key==='spotlight'?'spotlights':key==='interview'?'interviews':key+'s';const {error}=await db.from(table).delete().eq('id',id);if(error)alert(error.message);else await load();return}}
    if(t.dataset.saveRequest){const sel=document.querySelector(`.request-status[data-request-id="${t.dataset.saveRequest}"]`);const {error}=await db.from('service_requests').update({status:sel.value}).eq('id',t.dataset.saveRequest);if(error)alert(error.message);else await load()}
  });
  (async()=>{if(!db){gate.textContent='Connect Supabase to activate the admin studio. Copy js/supabase-config.js.example to js/supabase-config.js and add your project credentials.';return}const {data:{user}}=await db.auth.getUser();if(!user){location.href='auth.html';return}const {data:profile,error}=await db.from('profiles').select('full_name,role').eq('id',user.id).single();if(error||!profile||profile.role!=='admin'){gate.textContent='This account does not have admin access. Ask an existing ShelfTalk administrator to assign the admin role.';return}gate.hidden=true;app.hidden=false;$('userLabel').textContent=profile.full_name||user.email;$('signout').addEventListener('click',async()=>{await db.auth.signOut();location.href='auth.html'});await load()})();
})();
