const searchBooks=[
 {type:'book',title:'The Alchemist',author:'Paulo Coelho',genre:'fiction',country:'Brazil',rating:'4.7',image:'https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg',href:'book.html?id=alchemist',text:'following dreams journey self discovery'},
 {type:'book',title:'Tomorrow, and Tomorrow, and Tomorrow',author:'Gabrielle Zevin',genre:'fiction',country:'United States',rating:'4.8',image:'https://covers.openlibrary.org/b/isbn/9780593321201-L.jpg',href:'book.html?id=tomorrow',text:'friendship creativity ambition'},
 {type:'book',title:'Half of a Yellow Sun',author:'Chimamanda Ngozi Adichie',genre:'african',country:'Nigeria',rating:'4.8',image:'https://covers.openlibrary.org/b/isbn/9780007200286-L.jpg',href:'book.html?id=half-yellow-sun',text:'Nigeria Biafra war family love African literature'},
 {type:'book',title:'Things Fall Apart',author:'Chinua Achebe',genre:'african',country:'Nigeria',rating:'4.8',image:'https://covers.openlibrary.org/b/isbn/9780385474542-L.jpg',href:'book.html?id=things-fall-apart',text:'Igbo culture colonialism classic African literature'},
 {type:'book',title:'Atomic Habits',author:'James Clear',genre:'nonfiction',country:'United States',rating:'4.7',image:'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',href:'book.html?id=atomic-habits',text:'habits productivity personal development'},
 {type:'book',title:'Purple Hibiscus',author:'Chimamanda Ngozi Adichie',genre:'african',country:'Nigeria',rating:'4.7',image:'https://covers.openlibrary.org/b/isbn/9781616202415-L.jpg',href:'book.html?id=purple-hibiscus',text:'family faith freedom coming of age Nigeria'}
];
const searchAuthors=[
 {type:'author',title:'Chimamanda Ngozi Adichie',meta:'Nigeria · Novelist & storyteller',image:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=85',href:'author.html?id=amara',text:'Nigeria fiction African literature identity family'},
 {type:'author',title:'Anna Davis',meta:'United Kingdom · Writer & literary educator',image:'https://cdn.sanity.io/images/pbcwb2z8/production/f3ac5ca67e10668c6682cc80113993aa4a2efacb-5760x3840.jpg?auto=format&fit=crop&w=900&q=80',href:'author.html?id=anna',text:'writer editor literary education'},
 {type:'author',title:'Anna Michels',meta:'United States · Author & editorial director',image:'https://images.squarespace-cdn.com/content/v1/550d7c8be4b01d797b316def/1441245405887-UKB0XWPWROG129W82P39/image-asset.jpeg',href:'author.html?id=michels',text:'author editorial contemporary literature'}
];
const editorial=[
 {type:'interview',title:'ShelfTalk Conversations',meta:'Author interviews · video & audio',image:'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=900&q=85',href:'conversations.html',text:'author interview podcast conversation'},
 {type:'journal',title:'The stories we carry across borders',meta:'ShelfTalk Journal · Culture & Books',image:'https://images.unsplash.com/photo-1455885666463-6e8d0f5e9f95?auto=format&fit=crop&w=900&q=85',href:'journal.html',text:'literature culture readers stories'},
 {type:'event',title:'Global Readers Gathering',meta:'Literary event · Online',image:'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=900&q=85',href:'events.html',text:'readers author event community'},
 {type:'club',title:'The World Shelf Book Club',meta:'Book club · Global readers',image:'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=900&q=85',href:'book-clubs.html',text:'book club reading community'}
];
let currentType='all';
const qEl=document.getElementById('globalSearch'), resultsEl=document.getElementById('searchResults'), countEl=document.getElementById('searchCount');
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function render(){const q=qEl.value.trim().toLowerCase();const genres=[...document.querySelectorAll('.genre-filter:checked')].map(x=>x.value);const countries=[...document.querySelectorAll('.country-filter:checked')].map(x=>x.value);let all=[...searchBooks,...searchAuthors,...editorial];let filtered=all.filter(x=>currentType==='all'||x.type===currentType).filter(x=>!q||`${x.title} ${x.author||''} ${x.meta||''} ${x.text||''} ${x.genre||''} ${x.country||''}`.toLowerCase().includes(q)).filter(x=>!genres.length||genres.includes(x.genre)).filter(x=>!countries.length||countries.includes(x.country));countEl.textContent=`${filtered.length} result${filtered.length===1?'':'s'}${q?` for “${qEl.value.trim()}”`:''}`;if(!filtered.length){resultsEl.innerHTML='<div class="result-empty"><h3>No matches yet</h3><p>Try a broader search or clear a filter.</p></div>';return}resultsEl.innerHTML=filtered.map(x=>`<a class="result-card ${x.type}-result" href="${x.href}"><img loading="lazy" src="${x.image}" alt="${esc(x.title)}"><div><span class="eyebrow">${esc(x.type)}</span><h3>${esc(x.title)}</h3><p class="result-meta">${esc(x.meta||`${x.author} · ${x.country||''}`)}</p>${x.rating?`<p>★ ${x.rating}</p>`:''}<p>${esc(x.text||'Explore this ShelfTalk destination.')}</p></div></a>`).join('')}
document.getElementById('searchForm').addEventListener('submit',e=>{e.preventDefault();render();history.replaceState({},'',`search.html${qEl.value?'?q='+encodeURIComponent(qEl.value):''}`)});
document.querySelectorAll('.search-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.search-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentType=b.dataset.type;render()}));
document.querySelectorAll('.genre-filter,.country-filter').forEach(x=>x.addEventListener('change',render));
document.getElementById('clearFilters').addEventListener('click',()=>{document.querySelectorAll('.genre-filter,.country-filter').forEach(x=>x.checked=false);render()});
const initial=new URLSearchParams(location.search).get('q');if(initial)qEl.value=initial;render();
